[package]
name = "rust_proj"
version = "0.1.0"
authors = ["TJ DeVries <devries.timothyj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
